on:
    push:
        branches: [main]
        tags: [v*]

jobs:

    build:
        name: Build & Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org
                  always-auth: true
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Release
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
